{
	"version": 1591303529,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/backgroundtile.png",
		"images/player-sheet0.png",
		"images/solidtile.png",
		"images/jumpthrutile.png",
		"images/uparrw-sheet0.png",
		"images/rightarrw-sheet0.png",
		"images/leftarrw-sheet0.png",
		"images/downarrw-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite-sheet0.png",
		"media/sanic - 01 - through the pingas and flames.ogg",
		"media/sanic - 02 - cruel angels pingas.ogg",
		"media/sanic - 03 - crazy pingas.ogg",
		"media/sanic - 04 - green trill zone.ogg",
		"media/sanic - 05 - pingas sonata.ogg",
		"media/sanic - 06 - pingas sonata techno version.ogg",
		"media/sanic - 07 - sanic ex.ogg",
		"media/sanic - 08 - sanic hegihog theme.ogg",
		"media/sanic - 09 - sanic main theme.ogg",
		"media/sanic - 10 - sanic rimix.ogg",
		"media/sanic - 11 - sanic theme in g major.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"penumbra.png",
		"pathfind.js"
	]
}